services:

  worldtime:
    image: bletvaska/python
    ports:
    - 80:8000
    volumes:
    - ./app:/app
    command: [
      "uvicorn", "main:app", 
      "--reload", 
      "--host=0.0.0.0", 
      "--port=8000"
      # "--log-level=critical"
    ]

  loki:
    image: grafana/loki
    volumes:
    - loki:/loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090 
    volumes:
    - ./configs/prometheus:/etc/prometheus
    - prometheus:/prometheus

volumes:
  loki:
  grafana:
  prometheus:
