version: "3"

services:
  worldtime:
    image: bletvaska/python
    volumes:
    - ./app:/app
    ports:
    - 80:8000
    command: [
      "uvicorn", "main:app", "--reload",
      "--host=0.0.0.0", "--port=8000", "--log-level=critical"
    ]
    healthcheck:
      test: ["CMD", "http", "--check-status", "get", "http://localhost:8000/api/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 100M
        reservations:
          cpus: "0.25"
          memory: 50M

  loki:
    image: grafana/loki
    volumes:
    - loki:/loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

  prometheus:
    image: bitnami/prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus:/opt/bitnami/prometheus/data
    - ./config/prometheus/:/opt/bitnami/prometheus/conf/

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    ports:
    - 9100:9100


volumes:
  loki:
  grafana:
  prometheus:
