version: "3"


services:
    fastapi:
        image: bletvaska/python
        ports:
        - 8080:8080
        volumes:
        - ./app:/app
        user: "${UID:-1000}:${GID:-1000}"
        command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload


    toolbox:
        image: bletvaska/toolbox
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
        - ./app:/app
        working_dir: /app

