version: "3"

services:
  worldtime:
    image: bletvaska/python
    volumes:
    - ./app:/app
    ports:
    - 80:8000
    command: python3 main.py
    # - uvicorn "main:app"
    # - --host 0.0.0.0
    # - --port 8000
    # - --reload
    # - --log-level critical
    healthcheck:
      test: ["CMD", "http", "--check-status", "get", "http://localhost:8000/api/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s

  loki:
    image: grafana/loki
    volumes:
    - loki:/loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

  prometheus:
    image: bitnami/prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus:/opt/bitnami/prometheus/data
    - ./config/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml


volumes:
  loki:
  grafana:
  prometheus:
