version: "3"


services:
    worldtime:
        image: worldtime
        ports:
        - 8080:8080
        volumes:
        - ./app:/app
#        user: "${UID:-1000}:${GID:-1000}"
        #command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload

#     fastapi:
#         image: bletvaska/python
#         ports:
#         - 8080:8080
#         volumes:
#         - ./app:/app
#         user: "${UID:-1000}:${GID:-1000}"
#         command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
# #         logging:
# #             driver: fluentd
# #             options:
# #                 fluentd-address: fluentd:24224
# 

    toolbox:
        image: bletvaska/toolbox
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
        - ./app:/app
        working_dir: /app


    loki:
        image: grafana/loki
        ports:
        - 3100:3100


    grafana:
        image: grafana/grafana
        user: "${UID:-1000}:${GID:-1000}"
        ports:
        - 3000:3000
        volumes:
        - ./config/grafana:/var/lib/grafana


    prometheus:
        image: bitnami/prometheus
#        image: prom/prometheus
        ports:
        - 9090:9090
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
#        - ./config/prometheus:/opt/bitnami/promethues
        - ./config/prometheus/data:/opt/bitnami/prometheus/data
        - ./config/prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml



#     fluentd:
#         # image: fluent/fluentd
#         image: grafana/fluent-plugin-loki:master
#         volumes:
#         - ./config/fluentd/conf:/fluentd/etc
#         ports:
#         - 24224:24224
#         - 24224:24224/udp
#         environment:
#             LOKI_URL: http://loki:3100
#             LOKI_USERNAME:
#             LOKI_PASSWORD:
# 
