version: "3"

services:
  worldtime:
    volumes:
    - ./app:/app
    ports:
    - 80:8000
    image: bletvaska/python
    command: python3 main.py
    # - uvicorn "main:app"
    # - --host 0.0.0.0
    # - --port 8000
    # - --reload
    # - --log-level critical

  loki:
    image: grafana/loki
    volumes:
    - loki:/loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

volumes:
  loki:
  grafana:
