version: "3"

services:
  worldtime:
    image: bletvaska/python
    volumes:
    - ./app:/app
    ports:
    - 80:8000
    tty: true
    command: [
     "uvicorn", "main:app", 
     "--host", "0.0.0.0",
     "--reload",
     "--log-level=critical"
    ]

  loki:
    image: grafana/loki
    volumes:
    - loki:/loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

  prometheus:
    image: bitnami/prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus:/opt/bitnami/prometheus/data
    - ./configs/prometheus/:/opt/bitnami/prometheus/conf/

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'


volumes:
  loki:
  grafana:
  prometheus:
