version: "3"

services:
  worldtime:
    image: bletvaska/python
    volumes:
    - ./app:/app
    ports:
    - 80:8000
    tty: true
    command: [
     "uvicorn", "main:app", 
     "--host", "0.0.0.0",
     "--reload",
     "--log-level=critical"
    ]

  loki:
    image: grafana/loki
    volumes:
    - loki:/loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana


volumes:
  loki:
  grafana:
