services:

  worldtime:
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    image: bletvaska/python
    command: [
      "uvicorn", "main:app", "--host", "0.0.0.0", "--reload"
    ]

  loki:
    image: grafana/loki
    volumes:
    - loki:/loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

  prometheus:
    image: bitnami/prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus:/opt/bitnami/prometheus/data
    - ./configs/prometheus:/opt/bitnami/prometheus/conf/

volumes:
  loki:
  grafana:
  prometheus:
