services:

  worldtime:
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    image: bletvaska/python
    command: [
      "uvicorn", "main:app", "--host", "0.0.0.0", "--reload"
    ]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 100M
        reservations:
          cpus: "0.25"
          memory: 50M
    # healthcheck:
    #   test: [
    #     "CMD", "/home/pythonista/.local/bin/http", "--check-status", "get", "http://localhost:8000/healthz"
    #   ]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 10s

  loki:
    image: grafana/loki
    volumes:
    - loki:/loki

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana

  prometheus:
    image: bitnami/prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus:/opt/bitnami/prometheus/data
    - ./configs/prometheus:/opt/bitnami/prometheus/conf/

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'

volumes:
  loki:
  grafana:
  prometheus:
