global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: grafana
    static_configs:
    - targets: ['grafana:3000']

  - job_name: loki
    static_configs:
    - targets: ['loki:3100']

  - job_name: worldtime
    static_configs:
    - targets: ['worldtime:8000']

  - job_name: node_exporter
    static_configs:
    - targets: ['node_exporter:9100']

