global:
  scrape_interval: 15s

scrape_configs:
  - job_name: infrastructure
    metrics_path: "/metrics"
    static_configs:
    - targets: [
      'prometheus:9090',
      'grafana:3000',
      'loki:3100'
      ]
