scrape_configs:
- job_name: infrastructure
  scrape_interval: 60s
  metrics_path: "/metrics"
  static_configs:
  - targets: [
      'grafana:3000',
      'loki:3100',
      'prometheus:9090'
  ]

- job_name: wordltime
  static_configs:
  - targets: [
    'worldtime:80'
  ]
